# Generated by Django 4.2.6 on 2023-10-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adtype_remove_ad_cost_share_alter_ad_ad_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adtype',
            name='name',
            field=models.CharField(choices=[('1', '0011'), ('2', '1011'), ('3', '1111'), ('4', '1010')], default='1', max_length=200),
        ),
    ]
