# Generated by Django 4.2.6 on 2023-10-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_adtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adtype',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
