# Generated by Django 4.2.6 on 2023-10-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtype',
            name='limit_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='adtype',
            name='limit_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='adtype',
            name='cost_share',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
